patrolling_node:
  ros__parameters:
    waypoints: ["wp1", "obs", "wp2", "wp3", "wp4", "wp5", "wp6"]
    wp1: [-0.059, -2.47]
    wp2: [-2.62, 0.885]
    wp3: [-1.23, 4.82]
    wp4: [2.08, 3.02] 
    wp5: [-1.46, 1.06]
    wp6: [0.0, 0.0]
    obs: [1.57, -0.523]
    error: [999.0, 999.0]
    
